name: SystemX-HIS

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bkkcs-api-server
    restart: unless-stopped
    ports:
      - "${PORT:-3005}:3005"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
