version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: his-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    build: .
    container_name: his-sdk
    ports:
      - "9991:8080"
    env_file:
      - .env
    volumes:
      - ./assets:/app/assets
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
