server {
    listen 80;
    server_name his-api.systemx-th.com;

    # Max upload size (ต้องตรง APP_MAXSIZE ใน .env)
    client_max_body_size 10M;

    # Proxy to app container
    location / {
        proxy_pass         http://127.0.0.1:9991;
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        proxy_read_timeout  300;
        proxy_send_timeout  300;
        proxy_connect_timeout 60;
    }
}
